### ISSUE TITLE
属性テーブルのbit並びが逆？

### ISSUE THREAD

**Issue by taisukef** [suzukiplan/mgp-fc#1]
bit 7〜6 : 左上2x2マスのパレット番号（%00, %01, %10, %11）
bit 5〜4 : 右上2x2マスのパレット番号（%00, %01, %10, %11）
bit 3〜2 : 左下2x2マスのパレット番号（%00, %01, %10, %11）
bit 1〜0 : 右下2x2マスのパレット番号（%00, %01, %10, %11）

とありますが、実際試したところ

bit 7〜6 : 右下2x2マスのパレット番号（%00, %01, %10, %11）
bit 5〜4 : 左下2x2マスのパレット番号（%00, %01, %10, %11）
bit 3〜2 : 右上2x2マスのパレット番号（%00, %01, %10, %11）
bit 1〜0 : 左上2x2マスのパレット番号（%00, %01, %10, %11）

の順でした

**Comment by suzukiplan** [comment]
ご指摘ありがとうございます。思いっきり誤植でした。
ご指摘されているビットレイアウトが正しいので、修正しておきます。

**Comment by suzukiplan** [comment]
修正done: https://github.com/suzukiplan/mgp-fc/commit/0793064dbc20b7707ca5eff026a786fb1781ccd9
